root: ./

redirects:
  clarity/: overview.md
  clarity/crash-course: clarity/crash-course.md
  clarity/language-functions: clarity/language-functions.md
  clarity/language-keywords: clarity/language-keywords.md
  clarity/language-types: clarity/language-types.md
  clarity/noteworthy-contracts/bns-contract: clarity/example-contracts/bns.md
  clarity/noteworthy-contracts/stacking-contract: clarity/example-contracts/stacking.md
  clarity/noteworthy-contracts/xbtc: clarity/example-contracts.md
  clarity/sample-contracts: clarity/example-contracts.md
  clarity/security/: clarity/decidability.md
  clarity/security/decidable: clarity/decidability.md
  contribute/: /
  contribute/docs: /
  contribute/translations: /
  cookbook/: tutorials/hello-stacks-quickstart-tutorial.md
  cookbook/creating-an-ft: tutorials/hello-stacks-quickstart-tutorial.md
  cookbook/creating-an-nft: tutorials/hello-stacks-quickstart-tutorial.md
  cookbook/get-sats-per-stx: tutorials/hello-stacks-quickstart-tutorial.md
  cookbook/parse-a-btc-tx: tutorials/hello-stacks-quickstart-tutorial.md
  cookbook/post-conditions: tutorials/hello-stacks-quickstart-tutorial.md
  cookbook/sending-bitcoin-with-hiro-wallet: tutorials/hello-stacks-quickstart-tutorial.md
  cookbook/stacks-js-auth: tutorials/hello-stacks-quickstart-tutorial.md
  cookbook/stacks-js-sending-transactions: tutorials/hello-stacks-quickstart-tutorial.md
  cookbook/verifying-a-btc-tx-was-mined: tutorials/hello-stacks-quickstart-tutorial.md
  gaia/: stacks-in-depth/gaia.md
  gaia/configuration: stacks-in-depth/gaia/configuration.md
  gaia/deploy-gaia-hub: stacks-in-depth/gaia/deploy-gaia-hub.md
  gaia/gaia-on-ec2: stacks-in-depth/gaia/gaia-on-ec2.md
  gaia/setup-linux: stacks-in-depth/gaia/setup-linux.md
  gaia/setup-mac: stacks-in-depth/gaia/setup-mac.md
  glossary/: /
  intro: /
  nakamoto/: nakamoto-upgrade/what-is-the-nakamoto-release.md
  nakamoto/bitcoin-mev-mitigation: nakamoto-upgrade/nakamoto-in-10-minutes.md
  nakamoto/block-production: nakamoto-upgrade/nakamoto-in-10-minutes.md
  nakamoto/neon: nakamoto-upgrade/testnets/neon.md
  nakamoto/signer: nakamoto-upgrade/running-a-signer.md
  nakamoto/stacking: nakamoto-upgrade/stacking-flow.md
  next-steps/: /
  nodes-and-miners/: stacks-in-depth/nodes-and-miners.md
  nodes-and-miners/digitalocean: stacks-in-depth/nodes-and-miners/digitalocean.md
  nodes-and-miners/hosted-nodes: stacks-in-depth/nodes-and-miners/hosted-nodes.md
  nodes-and-miners/miner-costs-and-fees: stacks-in-depth/nodes-and-miners/miner-costs-and-fees.md
  nodes-and-miners/miner-mainnet: stacks-in-depth/nodes-and-miners/miner-mainnet.md
  nodes-and-miners/miner-testnet: stacks-in-depth/nodes-and-miners/miner-testnet.md
  nodes-and-miners/quicknode: stacks-in-depth/nodes-and-miners/quicknode.md
  nodes-and-miners/run-a-node: stacks-in-depth/nodes-and-miners/run-a-node.md
  nodes-and-miners/stacks-node-configuration: stacks-in-depth/nodes-and-miners/stacks-node-configuration.md
  nodes-and-miners/verify-miner: stacks-in-depth/nodes-and-miners/verify-miner.md
  services-using-stacks/defi: /
  services-using-stacks/more: /
  services-using-stacks/nft: /
  services-using-stacks/stacks-info-sites: /
  services-using-stacks/wallets: /
  stacks-academy/: stacks-101/what-is-stacks.md
  stacks-academy/accounts: stacks-101/accounts.md
  stacks-academy/authentication: stacks-101/authentication.md
  stacks-academy/bns: stacks-101/bitcoin-name-system.md
  stacks-academy/btc-connection: stacks-101/bitcoin-connection.md
  stacks-academy/microblocks: stacks-101/microblocks.md
  stacks-academy/mining: stacks-101/mining.md
  stacks-academy/network: stacks-101/network.md
  stacks-academy/post-conditions: stacks-101/post-conditions.md
  stacks-academy/proof-of-transfer: stacks-101/proof-of-transfer.md
  stacks-academy/sips: stacks-101/sips.md
  stacks-academy/stacking: stacks-101/stacking.md
  stacks-academy/stacks-blockchain-api: stacks-101/stacks-blockchain-api.md
  stacks-academy/technical-specs: stacks-101/technical-specifications.md
  stacks-academy/testnet: stacks-101/testnet.md
  stacks-academy/transactions: stacks-101/transactions.md
  stacks-academy/what-is-stacks: stacks-101/what-is-stacks.md
  stacks-academy/whitepapers: stacks-101/whitepapers.md
  tutorials/: tutorials/hello-stacks-quickstart-tutorial.md
  tutorials/community-tutorials: tutorials/community-tutorials.md
  tutorials/hello-stacks: tutorials/hello-stacks-quickstart-tutorial.md
